#!/usr/bin/env python3
"""
collector MCP Server
Generated by Morpheus MCP Generator

This collects data
"""

import asyncio
import json
import logging
from typing import Any, Dict, Optional, Union
import httpx
import requests
from fastmcp import FastMCP

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Create FastMCP server instance
mcp = FastMCP("collector")

# HTTP client for API calls
http_client = httpx.AsyncClient(timeout=30.0)

# Generate tools

@mcp.tool()
def get_health() -> Dict[str, Any]:
    """
    Tool generated from GET health API. Health
    
    Args:
    No parameters
    
    Returns:
        Dict containing the result of the tool execution
    """
    try:
        result_data = {}

        # Call health: GET http://localhost:8000/health
        url = "http://localhost:8000/health"
        params = {}
        response = requests.request("GET", url, )
        response.raise_for_status()
        api_response = response.json()
        result_data["api_response"] = api_response

        return {"success": True, "data": result_data}
    except Exception as e:
        logger.error(f"Error in tool get_health: {e}")
        return {"error": str(e), "success": False}


@mcp.tool()
def get_listdatabases() -> Dict[str, Any]:
    """
    Tool generated from GET list_databases API. List Databases
    
    Args:
    No parameters
    
    Returns:
        Dict containing the result of the tool execution
    """
    try:
        result_data = {}

        # Call list_databases: GET http://localhost:8000/databases
        url = "http://localhost:8000/databases"
        params = {}
        response = requests.request("GET", url, )
        response.raise_for_status()
        api_response = response.json()
        result_data["api_response"] = api_response

        return {"success": True, "data": result_data}
    except Exception as e:
        logger.error(f"Error in tool get_listdatabases: {e}")
        return {"error": str(e), "success": False}


@mcp.tool()
def get_metadata(db: Optional[str] = None) -> Dict[str, Any]:
    """
    Tool generated from GET get_metadata API. Get Metadata
    
    Args:
    db: Collected SQLite DB filename to read (see GET /databases). If omitted, the server's default database is used.
    
    Returns:
        Dict containing the result of the tool execution
    """
    try:
        result_data = {}

        # Call get_metadata: GET http://localhost:8000/metadata
        url = "http://localhost:8000/metadata"
        params = {}
        if db is not None:
            params["db"] = db
        response = requests.request("GET", url, params=params)
        response.raise_for_status()
        api_response = response.json()
        result_data["api_response"] = api_response

        return {"success": True, "data": result_data}
    except Exception as e:
        logger.error(f"Error in tool get_metadata: {e}")
        return {"error": str(e), "success": False}


@mcp.tool()
def get_listclusters(db: Optional[str] = None) -> Dict[str, Any]:
    """
    Tool generated from GET list_clusters API. List Clusters
    
    Args:
    db: Collected SQLite DB filename to read (see GET /databases). If omitted, the server's default database is used.
    
    Returns:
        Dict containing the result of the tool execution
    """
    try:
        result_data = {}

        # Call list_clusters: GET http://localhost:8000/clusters
        url = "http://localhost:8000/clusters"
        params = {}
        if db is not None:
            params["db"] = db
        response = requests.request("GET", url, params=params)
        response.raise_for_status()
        api_response = response.json()
        result_data["api_response"] = api_response

        return {"success": True, "data": result_data}
    except Exception as e:
        logger.error(f"Error in tool get_listclusters: {e}")
        return {"error": str(e), "success": False}


@mcp.tool()
def get_cluster(cluster_moid: str, db: Optional[str] = None) -> Dict[str, Any]:
    """
    Tool generated from GET get_cluster API. Get Cluster
    
    Args:
    cluster_moid: path parameter: cluster_moid
    db: Collected SQLite DB filename to read (see GET /databases). If omitted, the server's default database is used.
    
    Returns:
        Dict containing the result of the tool execution
    """
    try:
        result_data = {}

        # Call get_cluster: GET http://localhost:8000/clusters/{cluster_moid}
        # Build URL with path parameters
        url = "http://localhost:8000/clusters/{cluster_moid}"
        if cluster_moid is not None:
            url = url.replace("{cluster_moid}", str(cluster_moid))
        params = {}
        if db is not None:
            params["db"] = db
        response = requests.request("GET", url, params=params)
        response.raise_for_status()
        api_response = response.json()
        result_data["api_response"] = api_response

        return {"success": True, "data": result_data}
    except Exception as e:
        logger.error(f"Error in tool get_cluster: {e}")
        return {"error": str(e), "success": False}


@mcp.tool()
def get_clusterperf(cluster_moid: str, db: Optional[str] = None) -> Dict[str, Any]:
    """
    Tool generated from GET get_cluster_perf API. Get Cluster Perf
    
    Args:
    cluster_moid: path parameter: cluster_moid
    db: Collected SQLite DB filename to read (see GET /databases). If omitted, the server's default database is used.
    
    Returns:
        Dict containing the result of the tool execution
    """
    try:
        result_data = {}

        # Call get_cluster_perf: GET http://localhost:8000/clusters/{cluster_moid}/perf
        # Build URL with path parameters
        url = "http://localhost:8000/clusters/{cluster_moid}/perf"
        if cluster_moid is not None:
            url = url.replace("{cluster_moid}", str(cluster_moid))
        params = {}
        if db is not None:
            params["db"] = db
        response = requests.request("GET", url, params=params)
        response.raise_for_status()
        api_response = response.json()
        result_data["api_response"] = api_response

        return {"success": True, "data": result_data}
    except Exception as e:
        logger.error(f"Error in tool get_clusterperf: {e}")
        return {"error": str(e), "success": False}


@mcp.tool()
def get_listhosts(db: Optional[str] = None, cluster_moid: Optional[str] = None) -> Dict[str, Any]:
    """
    Tool generated from GET list_hosts API. List Hosts
    
    Args:
    db: Collected SQLite DB filename to read (see GET /databases). If omitted, the server's default database is used.
    cluster_moid: Filter hosts belonging to this cluster moid.
    
    Returns:
        Dict containing the result of the tool execution
    """
    try:
        result_data = {}

        # Call list_hosts: GET http://localhost:8000/hosts
        url = "http://localhost:8000/hosts"
        params = {}
        if db is not None:
            params["db"] = db
        if cluster_moid is not None:
            params["cluster_moid"] = cluster_moid
        response = requests.request("GET", url, params=params)
        response.raise_for_status()
        api_response = response.json()
        result_data["api_response"] = api_response

        return {"success": True, "data": result_data}
    except Exception as e:
        logger.error(f"Error in tool get_listhosts: {e}")
        return {"error": str(e), "success": False}


@mcp.tool()
def get_host(host_id: str, db: Optional[str] = None) -> Dict[str, Any]:
    """
    Tool generated from GET get_host API. Get Host
    
    Args:
    host_id: path parameter: host_id
    db: Collected SQLite DB filename to read (see GET /databases). If omitted, the server's default database is used.
    
    Returns:
        Dict containing the result of the tool execution
    """
    try:
        result_data = {}

        # Call get_host: GET http://localhost:8000/hosts/{host_id}
        # Build URL with path parameters
        url = "http://localhost:8000/hosts/{host_id}"
        if host_id is not None:
            url = url.replace("{host_id}", str(host_id))
        params = {}
        if db is not None:
            params["db"] = db
        response = requests.request("GET", url, params=params)
        response.raise_for_status()
        api_response = response.json()
        result_data["api_response"] = api_response

        return {"success": True, "data": result_data}
    except Exception as e:
        logger.error(f"Error in tool get_host: {e}")
        return {"error": str(e), "success": False}


@mcp.tool()
def get_hostperf(host_id: str, db: Optional[str] = None) -> Dict[str, Any]:
    """
    Tool generated from GET get_host_perf API. Get Host Perf
    
    Args:
    host_id: path parameter: host_id
    db: Collected SQLite DB filename to read (see GET /databases). If omitted, the server's default database is used.
    
    Returns:
        Dict containing the result of the tool execution
    """
    try:
        result_data = {}

        # Call get_host_perf: GET http://localhost:8000/hosts/{host_id}/perf
        # Build URL with path parameters
        url = "http://localhost:8000/hosts/{host_id}/perf"
        if host_id is not None:
            url = url.replace("{host_id}", str(host_id))
        params = {}
        if db is not None:
            params["db"] = db
        response = requests.request("GET", url, params=params)
        response.raise_for_status()
        api_response = response.json()
        result_data["api_response"] = api_response

        return {"success": True, "data": result_data}
    except Exception as e:
        logger.error(f"Error in tool get_hostperf: {e}")
        return {"error": str(e), "success": False}


@mcp.tool()
def get_listvms(db: Optional[str] = None, host_id: Optional[str] = None, cluster: Optional[str] = None, power_state: Optional[str] = None) -> Dict[str, Any]:
    """
    Tool generated from GET list_vms API. List Vms
    
    Args:
    db: Collected SQLite DB filename to read (see GET /databases). If omitted, the server's default database is used.
    host_id: Filter VMs on this host.
    cluster: Filter VMs by cluster name (vms.cluster column).
    power_state: Filter by power state, e.g. 'poweredOn'.
    
    Returns:
        Dict containing the result of the tool execution
    """
    try:
        result_data = {}

        # Call list_vms: GET http://localhost:8000/vms
        url = "http://localhost:8000/vms"
        params = {}
        if db is not None:
            params["db"] = db
        if host_id is not None:
            params["host_id"] = host_id
        if cluster is not None:
            params["cluster"] = cluster
        if power_state is not None:
            params["power_state"] = power_state
        response = requests.request("GET", url, params=params)
        response.raise_for_status()
        api_response = response.json()
        result_data["api_response"] = api_response

        return {"success": True, "data": result_data}
    except Exception as e:
        logger.error(f"Error in tool get_listvms: {e}")
        return {"error": str(e), "success": False}


@mcp.tool()
def get_vm(vm_id: str, db: Optional[str] = None) -> Dict[str, Any]:
    """
    Tool generated from GET get_vm API. Get Vm
    
    Args:
    vm_id: path parameter: vm_id
    db: Collected SQLite DB filename to read (see GET /databases). If omitted, the server's default database is used.
    
    Returns:
        Dict containing the result of the tool execution
    """
    try:
        result_data = {}

        # Call get_vm: GET http://localhost:8000/vms/{vm_id}
        # Build URL with path parameters
        url = "http://localhost:8000/vms/{vm_id}"
        if vm_id is not None:
            url = url.replace("{vm_id}", str(vm_id))
        params = {}
        if db is not None:
            params["db"] = db
        response = requests.request("GET", url, params=params)
        response.raise_for_status()
        api_response = response.json()
        result_data["api_response"] = api_response

        return {"success": True, "data": result_data}
    except Exception as e:
        logger.error(f"Error in tool get_vm: {e}")
        return {"error": str(e), "success": False}


@mcp.tool()
def get_vmperf(vm_id: str, db: Optional[str] = None) -> Dict[str, Any]:
    """
    Tool generated from GET get_vm_perf API. Get Vm Perf
    
    Args:
    vm_id: path parameter: vm_id
    db: Collected SQLite DB filename to read (see GET /databases). If omitted, the server's default database is used.
    
    Returns:
        Dict containing the result of the tool execution
    """
    try:
        result_data = {}

        # Call get_vm_perf: GET http://localhost:8000/vms/{vm_id}/perf
        # Build URL with path parameters
        url = "http://localhost:8000/vms/{vm_id}/perf"
        if vm_id is not None:
            url = url.replace("{vm_id}", str(vm_id))
        params = {}
        if db is not None:
            params["db"] = db
        response = requests.request("GET", url, params=params)
        response.raise_for_status()
        api_response = response.json()
        result_data["api_response"] = api_response

        return {"success": True, "data": result_data}
    except Exception as e:
        logger.error(f"Error in tool get_vmperf: {e}")
        return {"error": str(e), "success": False}


@mcp.tool()
def get_clusterlinechart(moid: str, dataset: Optional[str] = None, metrics: Optional[str] = None, db: Optional[str] = None) -> Dict[str, Any]:
    """
    Tool generated from GET cluster_line_chart API. Cluster Line Chart
    
    Args:
    moid: path parameter: moid
    dataset: Which perf table to chart: 'historical' (utilization) or 'recent' (iops).
    metrics: Comma-separated metric columns to plot; defaults per entity/dataset.
    db: Collected SQLite DB filename to read (see GET /databases). If omitted, the server's default database is used.
    
    Returns:
        Dict containing the result of the tool execution
    """
    try:
        result_data = {}

        # Call cluster_line_chart: GET http://localhost:8000/charts/line/cluster/{moid}
        # Build URL with path parameters
        url = "http://localhost:8000/charts/line/cluster/{moid}"
        if moid is not None:
            url = url.replace("{moid}", str(moid))
        params = {}
        if dataset is not None:
            params["dataset"] = dataset
        if metrics is not None:
            params["metrics"] = metrics
        if db is not None:
            params["db"] = db
        response = requests.request("GET", url, params=params)
        response.raise_for_status()
        api_response = response.json()
        result_data["api_response"] = api_response

        return {"success": True, "data": result_data}
    except Exception as e:
        logger.error(f"Error in tool get_clusterlinechart: {e}")
        return {"error": str(e), "success": False}


@mcp.tool()
def get_hostlinechart(host_id: str, dataset: Optional[str] = None, metrics: Optional[str] = None, db: Optional[str] = None) -> Dict[str, Any]:
    """
    Tool generated from GET host_line_chart API. Host Line Chart
    
    Args:
    host_id: path parameter: host_id
    dataset: Which perf table to chart: 'historical' (utilization) or 'recent' (iops).
    metrics: Comma-separated metric columns to plot; defaults per entity/dataset.
    db: Collected SQLite DB filename to read (see GET /databases). If omitted, the server's default database is used.
    
    Returns:
        Dict containing the result of the tool execution
    """
    try:
        result_data = {}

        # Call host_line_chart: GET http://localhost:8000/charts/line/host/{host_id}
        # Build URL with path parameters
        url = "http://localhost:8000/charts/line/host/{host_id}"
        if host_id is not None:
            url = url.replace("{host_id}", str(host_id))
        params = {}
        if dataset is not None:
            params["dataset"] = dataset
        if metrics is not None:
            params["metrics"] = metrics
        if db is not None:
            params["db"] = db
        response = requests.request("GET", url, params=params)
        response.raise_for_status()
        api_response = response.json()
        result_data["api_response"] = api_response

        return {"success": True, "data": result_data}
    except Exception as e:
        logger.error(f"Error in tool get_hostlinechart: {e}")
        return {"error": str(e), "success": False}


@mcp.tool()
def get_vmlinechart(vm_id: str, dataset: Optional[str] = None, metrics: Optional[str] = None, db: Optional[str] = None) -> Dict[str, Any]:
    """
    Tool generated from GET vm_line_chart API. Vm Line Chart
    
    Args:
    vm_id: path parameter: vm_id
    dataset: Which perf table to chart: 'historical' (utilization) or 'recent' (iops).
    metrics: Comma-separated metric columns to plot; defaults per entity/dataset.
    db: Collected SQLite DB filename to read (see GET /databases). If omitted, the server's default database is used.
    
    Returns:
        Dict containing the result of the tool execution
    """
    try:
        result_data = {}

        # Call vm_line_chart: GET http://localhost:8000/charts/line/vm/{vm_id}
        # Build URL with path parameters
        url = "http://localhost:8000/charts/line/vm/{vm_id}"
        if vm_id is not None:
            url = url.replace("{vm_id}", str(vm_id))
        params = {}
        if dataset is not None:
            params["dataset"] = dataset
        if metrics is not None:
            params["metrics"] = metrics
        if db is not None:
            params["db"] = db
        response = requests.request("GET", url, params=params)
        response.raise_for_status()
        api_response = response.json()
        result_data["api_response"] = api_response

        return {"success": True, "data": result_data}
    except Exception as e:
        logger.error(f"Error in tool get_vmlinechart: {e}")
        return {"error": str(e), "success": False}


@mcp.tool()
def get_clustercapacitypie(moid: str, resource: Optional[str] = None, db: Optional[str] = None) -> Dict[str, Any]:
    """
    Tool generated from GET cluster_capacity_pie API. Cluster Capacity Pie
    
    Args:
    moid: path parameter: moid
    resource: Capacity to break down: storage|logical|memory|cpu.
    db: Collected SQLite DB filename to read (see GET /databases). If omitted, the server's default database is used.
    
    Returns:
        Dict containing the result of the tool execution
    """
    try:
        result_data = {}

        # Call cluster_capacity_pie: GET http://localhost:8000/charts/pie/cluster/{moid}/capacity
        # Build URL with path parameters
        url = "http://localhost:8000/charts/pie/cluster/{moid}/capacity"
        if moid is not None:
            url = url.replace("{moid}", str(moid))
        params = {}
        if resource is not None:
            params["resource"] = resource
        if db is not None:
            params["db"] = db
        response = requests.request("GET", url, params=params)
        response.raise_for_status()
        api_response = response.json()
        result_data["api_response"] = api_response

        return {"success": True, "data": result_data}
    except Exception as e:
        logger.error(f"Error in tool get_clustercapacitypie: {e}")
        return {"error": str(e), "success": False}


@mcp.tool()
def get_hostcapacitypie(host_id: str, db: Optional[str] = None) -> Dict[str, Any]:
    """
    Tool generated from GET host_capacity_pie API. Host Capacity Pie
    
    Args:
    host_id: path parameter: host_id
    db: Collected SQLite DB filename to read (see GET /databases). If omitted, the server's default database is used.
    
    Returns:
        Dict containing the result of the tool execution
    """
    try:
        result_data = {}

        # Call host_capacity_pie: GET http://localhost:8000/charts/pie/host/{host_id}/capacity
        # Build URL with path parameters
        url = "http://localhost:8000/charts/pie/host/{host_id}/capacity"
        if host_id is not None:
            url = url.replace("{host_id}", str(host_id))
        params = {}
        if db is not None:
            params["db"] = db
        response = requests.request("GET", url, params=params)
        response.raise_for_status()
        api_response = response.json()
        result_data["api_response"] = api_response

        return {"success": True, "data": result_data}
    except Exception as e:
        logger.error(f"Error in tool get_hostcapacitypie: {e}")
        return {"error": str(e), "success": False}


@mcp.tool()
def get_clusterscapacitypie(resource: Optional[str] = None, db: Optional[str] = None) -> Dict[str, Any]:
    """
    Tool generated from GET clusters_capacity_pie API. Clusters Capacity Pie
    
    Args:
    resource: Consumed metric to compare: storage|logical|memory|cpu.
    db: Collected SQLite DB filename to read (see GET /databases). If omitted, the server's default database is used.
    
    Returns:
        Dict containing the result of the tool execution
    """
    try:
        result_data = {}

        # Call clusters_capacity_pie: GET http://localhost:8000/charts/pie/clusters/capacity
        url = "http://localhost:8000/charts/pie/clusters/capacity"
        params = {}
        if resource is not None:
            params["resource"] = resource
        if db is not None:
            params["db"] = db
        response = requests.request("GET", url, params=params)
        response.raise_for_status()
        api_response = response.json()
        result_data["api_response"] = api_response

        return {"success": True, "data": result_data}
    except Exception as e:
        logger.error(f"Error in tool get_clusterscapacitypie: {e}")
        return {"error": str(e), "success": False}


@mcp.tool()
def get_clusterstoragecontainerspie(moid: str, metric: Optional[str] = None, db: Optional[str] = None) -> Dict[str, Any]:
    """
    Tool generated from GET cluster_storage_containers_pie API. Cluster Storage Containers Pie
    
    Args:
    moid: path parameter: moid
    metric: Slice value: consumed|capacity|freespace.
    db: Collected SQLite DB filename to read (see GET /databases). If omitted, the server's default database is used.
    
    Returns:
        Dict containing the result of the tool execution
    """
    try:
        result_data = {}

        # Call cluster_storage_containers_pie: GET http://localhost:8000/charts/pie/cluster/{moid}/storage-containers
        # Build URL with path parameters
        url = "http://localhost:8000/charts/pie/cluster/{moid}/storage-containers"
        if moid is not None:
            url = url.replace("{moid}", str(moid))
        params = {}
        if metric is not None:
            params["metric"] = metric
        if db is not None:
            params["db"] = db
        response = requests.request("GET", url, params=params)
        response.raise_for_status()
        api_response = response.json()
        result_data["api_response"] = api_response

        return {"success": True, "data": result_data}
    except Exception as e:
        logger.error(f"Error in tool get_clusterstoragecontainerspie: {e}")
        return {"error": str(e), "success": False}


if __name__ == "__main__":
    mcp.run()
